networks:
  app-network:
    driver: bridge
    name: app-network
  app-shared-network:
    external: true
    name: app-shared-network

secrets:
  private_key:
    file: ./private.pem
  public_key:
    file: ./public.pem

services:
  app-staging:
    image: phunpt01/nodejs-backend:latest
    container_name: app-staging
    restart: always
    env_file:
      - .env.staging
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - app-network # Internal network for DB/Redis
      - app-shared-network # External network for ML service
    depends_on:
      postgres-staging:
        condition: service_healthy
      redis-staging:
        condition: service_healthy
    secrets:
      - private_key
      - public_key
    volumes:
      - app_logs_staging:/app/logs
    environment:
      - PRIVATE_KEY_PATH=/run/secrets/private_key
      - PUBLIC_KEY_PATH=/run/secrets/public_key
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:${SERVER_PORT}/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  postgres-staging:
    image: ${POSTGRES_IMAGE}
    container_name: postgres-staging
    restart: always
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      PGDATA: /var/lib/postgresql/${POSTGRES_VERSION}/docker
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - postgres_data_staging:/var/lib/postgresql
    networks:
      - app-network
      - app-shared-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis-staging:
    image: ${REDIS_IMAGE}
    container_name: redis-staging
    restart: always
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    command: >
      sh -c "
      redis-server 
      --requirepass ${REDIS_PASSWORD} 
      --user ${REDIS_USERNAME} on '>${REDIS_USER_PASSWORD}' '~*' '&*' '+@all'
      "
    volumes:
      - redis_data_staging:/data
    networks:
      - app-network # Only on internal network
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-h",
          "localhost",
          "-p",
          "6379",
          "--user",
          "${REDIS_USERNAME}",
          "--pass",
          "${REDIS_USER_PASSWORD}",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  postgres_data_staging:
    driver: local
  redis_data_staging:
    driver: local
  app_logs_staging:
    driver: local
